# Generated by Django 4.1.7 on 2023-03-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='hora_salida',
            field=models.TimeField(null=True, verbose_name='Hora de salida'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='img_placa',
            field=models.ImageField(max_length=255, unique=True, upload_to='placas/', verbose_name='Imagen Placa'),
        ),
    ]
