# Generated by Django 4.1.7 on 2023-03-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0002_alter_vehiculo_hora_salida_alter_vehiculo_img_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='hora_salida',
            field=models.TimeField(auto_now_add=True, verbose_name='Hora de salida'),
        ),
    ]
