# Generated by Django 4.1.7 on 2023-09-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0003_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name': 'Modelo Base', 'verbose_name_plural': 'Modelos Base'},
        ),
    ]
