# Generated by Django 4.1.7 on 2023-03-29 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0004_alter_vehiculo_img_placa_alter_vehiculo_placa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'verbose_name': 'Modelo Base', 'verbose_name_plural': 'Modelos Base'},
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='delete_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de eliminacion'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
