# Generated by Django 4.1.7 on 2023-05-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0005_alter_vehiculo_options_vehiculo_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='hora_ingreso',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hora de ingreso'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora_salida',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hora de salida'),
        ),
    ]
