# Generated by Django 4.1.7 on 2023-05-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0006_alter_vehiculo_hora_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='hora_salida',
            field=models.DateTimeField(null=True, verbose_name='Hora de salida'),
        ),
    ]
