# Generated by Django 4.1.7 on 2023-05-05 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculosApp', '0007_alter_vehiculo_hora_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='img_placa',
            field=models.ImageField(max_length=255, null=True, upload_to='placas/', verbose_name='Imagen Placa'),
        ),
    ]
