# Generated by Django 4.1.7 on 2023-03-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_rename_user_active_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=6, unique=True, verbose_name='Placa identificada')),
                ('img_placa', models.ImageField(max_length=255, unique=True, upload_to='', verbose_name='Imagen Placa')),
                ('hora_ingreso', models.TimeField(auto_now_add=True, verbose_name='Hora de ingreso')),
                ('hora_salida', models.TimeField(auto_now_add=True, verbose_name='Hora de salida')),
                ('salida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
            },
        ),
    ]
