# Generated by Django 4.1.7 on 2023-03-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_vehiculos_vehiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={},
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora_salida',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Hora de salida'),
        ),
    ]
