# Generated by Django 4.1.7 on 2023-09-19 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculosApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('C', 'Creación'), ('U', 'Actualización'), ('D', 'Eliminación')], max_length=1)),
                ('detalles', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehiculo_afectado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculosApp.vehiculo')),
            ],
        ),
    ]
