# Generated by Django 4.1.7 on 2023-09-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditoria',
            name='usuario',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='usuario_id',
            field=models.IntegerField(default=11),
            preserve_default=False,
        ),
    ]
