# Generated by Django 4.1.7 on 2023-09-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_auditoria_usuario_auditoria_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
